services:
  - type: web
    name: ffmpeg-service
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y ffmpeg && 
      pip install -r requirements.txt
    startCommand: gunicorn main:app --host 0.0.0.0 --port $PORT
    plan: starter
